// CURRENT USER
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_LOGOUT = "SET_USER_LOGOUT";

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

export const SET_CURRENT_MENU = 'SET_CURRENT_MENU';

export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH';